name = "auth"
account_id = "67056a4a1b6415e838230d16b71ec5f0"
compatibility_date = "2026-02-14"

main = "index.js"

[vars]
CLIENT_ID = "1472254712022700225"
REDIRECT_URI = "https://auth.auth.kvartsbuen3.workers.dev/callback"
